### ISSUE TITLE
allow creation of png files

### ISSUE THREAD

**Issue by matzke** [amagical-net/rails-latex#21]
nice work! 

i would like to render latex to png without having to convert the pdf to png

**Comment by baierjan** [comment]
That is generally a good idea, unfortunately I am not aware of any method how to render directly to png. However, you can use convert. Moreover, you can use convert and specify it directly in the tex file.

For example an _input.tex_ file:
```tex
\documentclass[convert={density=300,size=1024x768,outext=.png}]{standalone}
\begin{document}
Hi!
\end{document}
```
and then run ``pdflatex -shell-escape input`` and you will have _input.pdf_ and _input.png_
