### ISSUE TITLE
Write logfiles to stdout rather than filesystem?

### ISSUE THREAD

**Issue by afuhrtrumpet** [amagical-net/rails-latex#35]
I am trying to use rails-latex on Heroku and am having some issues, so I would like to be able to see the logfiles. However, Heroku does not keep anything written to /app/tmp, so the only way to read this is if the log files are written to stdout so they are included in Heroku logs.

Is there a way to do this, or to write the contents of the log to screen?

**Comment by phillipp** [comment]
I changed that part of the code to use Kernel.spawn instead of forks (gets rid of pdflatex output on stdout). To make the code simpler I removed double parsing, maybe the code works for you: https://github.com/phillipp/rails-latex/commit/d3a1ec4aa933b43535153f225e0db38130660ad8

**Comment by sebastianzillessen** [comment]
Any updates on this? Im thinking of using this gem for a project and it would be great to see, that this feature is working.

**Comment by macite** [comment]
I suggest that you could handle this yourself.

I added an exception handler with something like this:

        logger.error "Failed to create PDF..."

        log_file = e.message.scan(/\/.*\.log/).first
        if log_file && File.exists?(log_file)
            puts "--- Latex Log ---\n"
            puts File.read(log_file)
            puts "---    End    ---\n\n"
        end
