### ISSUE TITLE
RailsLatex::ProcessingError is not thrown when using layout

### ISSUE THREAD

**Issue by vanboom** [amagical-net/rails-latex#50]
I am building a PDF using a structure similar to your README example with a`layouts/application.pdf.erbtex` with a `yield` and a view template `show.pdf.erb` which contains the \begin{document} ... \end{document} section.

I am attempting to rescue exceptions in the controller.  When an processing error occurrs, the exception that is thrown is an ActionView::Template::Error.  How do we get the RailsLatex::ProcessingError exception?  

Interestingly, the development view (in red) shows that an RailsLatex::ProcessingError occurs, but the rescued exception comes back as ActionView::Template::Error.  The error message is the one generated by latex_to_pdf.rb "rails-latex failed: See ... for details"

**Comment by vanboom** [comment]
You can access the original RailsLatex::ProcessingError exception through the ActionView::Template::Error like...

```ruby
rescue ActionView::Template::Error => e
  original_e = e.original_exception
```

**Comment by brentkearney** [comment]
I had the same question, glad this was here. Note: Rails 6 replaced the `original_exception` method with `cause`, so:

```
rescue ActionView::Template::Error => error
  RailsLatex_ProcessingError = error.cause
```

🍻
