### ISSUE TITLE
RailsLatex::ProcessingError

### ISSUE THREAD

**Issue by maxwinkler07** [amagical-net/rails-latex#51]
When using this gem, it correctly generates the tex file but then displays : RailsLatex::ProcessingError.

I attach the logs for further information
[input.log](https://github.com/amagical-net/rails-latex/files/1962330/input.log)

Thanks in advance.

**Comment by baierjan** [comment]
You need to install latex/pdflatex on the machine. The attached log said it on the first line:
`No such file or directory - pdflatex`
