### ISSUE TITLE
Rails 7 support

### ISSUE THREAD

**Issue by andre-bare** [amagical-net/rails-latex#65]
This gem cannot be installed under Rails 7. Gemspec specifically excludes Rails 7. 

Any chance of a Rails 7 release?  
Given we now have 313 assertions failling out of 565, we really like this gem! 

Thanks
André

**Comment by allavena** [comment]
See https://github.com/amagical-net/rails-latex/pull/66

**Comment by baierjan** [comment]
Thanks @allavena for updating the gemspec, I will release the updated version shortly.

**Comment by EmmaB** [comment]
Just wanted to say: thanks so much for the Rails 7 compatible version. I was very relieved to find it here!
